# Generated by Django 4.1.5 on 2023-01-30 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Item', max_length=40)),
                ('amount', models.FloatField(default=0.0)),
                ('frequency', models.IntegerField(choices=[(1, 'daily'), (7, 'weekly'), (30, 'daily')], default=7)),
                ('budget_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.budget')),
            ],
        ),
    ]
