# Generated by Django 4.0.4 on 2023-02-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_amount_item_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='name',
            field=models.CharField(default='New Budget', max_length=40, unique=True),
        ),
    ]
