# Generated by Django 4.0.4 on 2023-02-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_budget_user_id_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instantiated',
            field=models.BooleanField(default=False),
        ),
    ]
